### ISSUE TITLE
renamefile: Add [description] tag for specific file description

### ISSUE THREAD

**Issue by firegurafiku** [korv/Jabref-plugins#9]
As you know, JabRef allows associating multiple files with single entry, and each of this files has optional description field. Let's consider the following example:

```
@PHDTHESIS{Freeman1999,
  author = {Freeman, Gordon},
  title = {Observation of Einstein-Podolsky-Rosen Entanglement
           on Supraquantum Structures by Induction Through Nonlinear
           Transuranic Crystal of Extremely Long Wavelength ({ELW})
           Pulse from Mode-Locked Source Array},
  school = {Massachusetts Institute of Technology},
  year = {1999},
  file = {Text:phd.pdf:PDF;Slides:slides.pdf:PDF},
  timestamp = {2015.01.14}
}
```

If you try to autorename this record, *renamefile* will produce two exactly same names for both thesis text and slides. I suggest you to add one more tag `[description]` to allow making distinct filenames like above. For given example, pattern `[year] [auth] - [shorttitle] - [description]` would produce names:

* `1999 Freeman - Observation of Einstein-Podolski-Rosen - Text.pdf` and
* `1999 Freeman - Observation of Einstein-Podolski-Rosen - Slides.pdf`

**Comment by korv** [comment]
Actually, the current version adds a number (starting with 1) to the file name if there is more than 1 file in the entry. Also note that currently the description field in the file entry gets lost after renaming:
{description:file.pdf:PDF} is converted to {:file.pdf:PDF}
I would suggest that you copy description in your fork.

**Comment by firegurafiku** [comment]
Yes, I noticed that your code completely removes description field and have already fixed that. At first, I had added support for [description] tag into your code and wanted to submit a pull request, but then I realized that description field gets erased and decided to do much more comprehensive refactoring instead. I changed a lot of things I didn't like, and in my experience nobody likes when their code is being criticized so I've counted the chance that my changes go back upstream as negligible, hence the fork. You may take a look on it [here](https://bitbucket.org/firegurafiku/jabref-renamefiles2) if you want, any comments and suggestions are welcome.
